# Generated by Django 4.0.4 on 2022-06-28 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snsapp', '0003_freepost_freecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecomment',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freepost',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
